name: Build and deploy Python app to Azure Web App - supplychaintest5

on:
  push:
    branches:
      - python-code
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - python-code

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m 
          pip install flask
          pip install streamlit
          pip install datetime
          pip install pandas==1.5.3
          pip install ydata_profiling
          pip install pydantic_settings
          pip install seaborn
          pip install matplotlib
          pip install setuptools
          pip install pandasai
          pip install numpy==1.26.4
          pip install langchain_openai

      - name: Copy flask_python.py to deployment directory
        run: cp flask_python.py .

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_706601D86378468CA65BD27DF7FF4663 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_556063F500724234844C27A50B784945 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80DFBBD0A589421B839B22AAA41FE819 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'supplychaintest5'
          slot-name: 'Production'
